config/routes.rb
Rails.application.routes.draw do

  get '/mypage' => 'mypage#index'

  devise_for :users

  root to: 'articles#index'

  resources :articles




  resources :users



end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController






  def index


    articles = current_user.articles
    articles = articles.where('title LIKE ?', "%#{params[:title]}%") if  params[:title].present?

    @articles = current_user.articles.page params[:page]
    # @users = User.page(params[:page]).per(10)


   end




  #  def show
  #   @user = User.find(params[:id])
  #   @users = User.article(params[:id])
  #   @users = User.article(params[:id])
  #   @articles = current_user.articles

  #  end






end

app/views/mypage/_search.html.erb
<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypage/index.html.erb
<p id="notice"><%= notice %></p>
<h1>マイページ</h1>
<div>
<%= render partial: "search" %>
<%= paginate @articles %>
</div>
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
      <td>
          <%= article.title %>
          <% article.tags.each do |tag| %>
            <span class="badge rounded-pill bg-primary"><%= tag.name%></span>
          <% end %>
      </td>
        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
          <%= link_to '編集', edit_article_path(article), class: "btn btn-warning" %>
          <%= link_to '削除', article, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>