config/routes.rb
Rails.application.routes.draw do

  get '/mypage' => 'mypage#index'

  devise_for :users

  root to: 'articles#index'

  resources :articles




  resources :users



end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "TOP", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in?%>
          <li class="nav-item">

            <%= link_to "マイページ", mypage_path, class: "nav-link active" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :elete, class: "nav-link active" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "サインアップ", new_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "サインイン", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
  <head>
    <title>WonderfulPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render partial: "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>

  </body>
 </html>